project:
  type: website

website:
  title: "TEA-DT Community Pulse Check"
  navbar:
    left:
      - href: about.qmd
        text: About
      - href: methodology.qmd
        text: Methodology
      - text: Survey Analysis and Results
        menu:
          - analysis.qmd
          - notebooks.qmd
    tools:
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/alan-turing-institute/teadt-community-survey
          - text: Report a Bug
            href:  https://github.com/alan-turing-institute/teadt-community-survey/issues
  repo-url: github.com/alan-turing-institute/teadt-community-survey
  repo-actions: [source, issue]

bibliography: refs.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



