---
tbl-colwidths: [10,45,45]
---

# List of Questions

::: {.callout-info}
On this page you will find a list of the survey's questions, split into the relevant sections.
:::

### Section 1: Background Information


| Number | Question | Response Options |
|:---|:---|:---:|
| Q1.1 | In which country is your organisation registered? | Global, United Kingdom, [List of all countries]  |
| Q1.2 | What is your role within your organisation? | Senior Management (e.g., CEO, CFO, CTO), Strategic/Business Lead (e.g., Business Unit Head, Project/Program Manager, Operations Manager), Strategic Advisor (e.g., Compliance Officer, Regulatory Affairs Manager, Legal Advisor), In-house Technical Specialist (e.g., Developer/Engineer, Data Scientist/Analyst, IT Specialist), Digital Twin Support Specialist (e.g., Ontology Developer, Dashboard Developer, Data Integration Specialist), Consultant/External Specialist (e.g., Industry Consultant, External IT Consultant, Freelance Technical Expert), Research and Development (e.g., Researcher/Academic, Innovation Specialist, Product Development Scientist), Other (Please specify) |
| Q1.3          | What are your primary responsibilities?                                                                                      | Strategic Direction, Budget Management, Ensuring Compliance, Project Leadership, Technical Decision-Making, Operational Management, Governance Influence, Research and Innovation, Other (Please specify)                                   |
| Q1.4          | What sector best represents your field of work?                                                                              | Aerospace, Architecture, Artificial Intelligence, Automotive, Aviation, Construction, Consumer Goods, Defence, Education, Electronics, Engineering, Environment and Conservation, Finance, Food and Agriculture, Freight, Healthcare, Information technology / Software, International Government, Local Government, Manufacturing, Maritime, Media, Mining, National Government, Energy, Oil and Gas, Place Leadership, Rail, Smart Cities, Supply Chain and Logistics, Technology, Telecommunications, Transport, Utilities, Waste and Recycling, Water, Other                                                               |
| Q1.5          | Has your organisation established one or more Digital Twins?                                                                 | Yes, No, Indirectly (We support clients or provide components for digital twins)                                                                                         |
| Q1.5b         | [If Yes or Indirectly] What type of digital twin? Please Select all that apply                                                | System, Place/Infrastructure Digital Twin, Product, Process, Physical asset, Other (Please specify)                                                                      |
| Q1.5c         | [If Yes or Indirectly] Which of the following best describes the purpose of the digital twin(s) you have (helped) establish? | Internal Operations, External Collaboration, Public Impact, Market / Customer Engagement, Research and Development, Other                                                |
| Q1.5d         | [If No] What is the main reason?                                                                                            | Unclear business case/ROI, insufficient digital awareness/skills, lack of goodwill/competence/data assurance trust in partner organisation, concerns re confidentiality of data, IPR, regulatory concerns re DP, info security, legal agreement barriers, Other                          |

### Section 2: Current Assurance Practices and Understanding

| Number | Question | Response Options |
|:---|:---|:---:|
| Q2.1          | What do you understand ‘assurance’ to mean in the context of your work?  | Open-ended response |
| Q2.2          | Which of the following assurance mechanisms do you currently rely on?     | Bias Reviews, Compliance Audits, Conformity Assessments, Stakeholder Feedback Systems, Impact Assessment, Risk Assessment, Information Security Reviews, Data Quality Checks, Formal Verification, Post-Implementation Evaluation, Service Continuity Management, Performance Monitoring, Operational Audits, Service Quality Reviews, Other (Please specify)  |
| Q2.3          | [If Q2.2 not empty] Which of the following properties do you currently consider when assuring your digital twinning technology? | Accountability, Contestability, Data Quality, Data Stewardship, Ethical Integrity, Evolution, Explainability, Fairness, Federation, Financial Performance, Fit-for-purpose, Governance, Interoperability, Openness, Public Good, Reliability/Robustness, Resilience / Fault-tolerance, Safety, Security, Sustainability, Transparency, Trustworthiness, Value Creation, None, Other (Please Specify) |
| Q2.4          | Who provides assurance within/for your organisation?                      | In-house assurance team, In-house, non-specialized team, External third-party, We provide assurance services for clients |
| Q2.5          | Have you considered sharing your asset-related data or models with other organisations to form connected digital twins? | Yes, No |
| Q2.5b         | [If Yes] When partnering with other organisations for building connected digital twins, how difficult is it to establish trust?       | Very Easy, Somewhat Easy, Neutral, Somewhat Difficult, Very Difficult (+ not applicable) |
| Q2.5c         | [If 2.5b selected as more difficult or neutral than easy] What are/were the major challenges to overcome? | Multiple Purpose |

### Section 3: Satisfaction with Assurance Practices

| Number | Question | Response Options |
|:---|:---|:---:|
| Q3.1 | To what extent do you agree with the following statements: | Strongly disagree, Disagree, Neutral, Agree, Strongly agree |
| Q3.2   | How satisfied are you currently with justification and documentation around your assurance process? | Very unsatisfied, Somewhat unsatisfied, Neutral, Somewhat satisfied, Very satisfied |

### Section 4: High-Level Assurance Goals and Ethical Frameworks

| Number | Question | Response Options |
|:---|:---|:---:|
| Q4.1 | Does your organisation have an established definition or framework for "trustworthy" and "ethical" digital twins? | Yes, No, I don’t know |
| Q4.2 | [If yes or something similar] If your framework is publicly available, please provide a link URL | Open-ended response |
| Q4.3          | How was this definition or framework developed? | Consensus-based process, Internal governance process, Developed by an external consultant, Reused/adapted existing framework/standards |
| Q4.4          | How valuable do you find high-level guiding principles in general?  | Not valuable at all, Slightly valuable, Moderately valuable, Very valuable, Extremely valuable |
| Q4.6          | How familiar are you with the Gemini principles? | Unfamiliar, Slightly Familiar, Somewhat Familiar, Familiar, Expert |
| Q4.7          | Please rate, for each Gemini principle individually, the extent to which it focuses on issues that you believe to be relevant for your work | Not Relevant, Slightly Relevant, Moderately Relevant, Very Relevant, Extremely Relevant |
| Q4.8          | For each of the following ethical principles, rate how challenging you find it to determine if you have adequately addressed the principle in practice | Not challenging at all, Slightly challenging, Moderately challenging, Very challenging, Extremely challenging  |
| Q4.9          | [Open-ended] For those rated very difficult or extremely difficult to operationalize, what are the main challenges you face? | Open-ended response  |

### Section 5: Communicating Assurance

| Number | Question | Response Options |
|:---|:---|:---:|
| Q5.1          | How do you currently communicate your project’s assurance strategies to your stakeholders or partner organisations? | Written Reports following established standards, Non-standardized written Reports, Meetings, Visual Aids, Digital Communications, Interactive Platforms, Not Systematically / ad hoc, Other |
| Q5.2          | Would a visual tool that helps you demonstrate and communicate how your evidence-based assurance measures align with key ethical goals enhance trust in your digital twin(s)? | Yes, No, I need to know more about this tool to decide |
| Q5.2b         | [If yes] What do you believe are the main benefits? | Open-ended response |
| Q5.2c         | [If no] Why not?  | Open-ended response |
| Q5.3          | How prepared do you feel to develop a structured argument for how your current assurance activities relate to broader ethical goals? | Very prepared, Somewhat prepared, Neutral, Somewhat unprepared, Not prepared at all |
| Q5.4          | What would prevent you from adopting a new trustworthy and ethical assurance tool?                   | Doesn’t fit into our governance process, Doesn’t integrate into our tech stack, Internal resistance, No time to spend on ethical assurance, Cost prohibitive, Lack of data |