name: tea_survey
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12.2
  - ipython=8.26.0
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - jupyterlab_widgets=3.0.10
  - matplotlib=3.8.3
  - notebook
  - numpy=1.26.4
  - pandas=2.2.1
  - plotly
  - scipy=1.14.0
  - seaborn=0.13.2
  - pip
