CONNECTION_STRING_ENV: str = "CONNECTION_STRING"
DATABASE_NAME_ENV: str = "DB_NAME"
COLLECTION_NAME_ENV: str = "COLLECTION_NAME"

USER_ID_STATE_KEY: str = "_id"
SECTOR_STATE_KEY: str = "sector"
LOCATION_STATE_KEY: str = "location"
ROLE_STATE_KEY: str = "role"
RESPONSIBILITIES_STATE_KEY: str = "primary_responsibilities"
